PUT http://localhost:8080/events/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZyYW5rQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ5MzQwNjI5LCJ1c2VyX2lkIjoxfQ.ZKLKTSsXvraOeBXUoWdq1yebpGa9oO9jo6w8NC3zfQs

{
    "name": "Blockchain and Cryptocurrency Workshop",
    "description": "Dive into the world of blockchain technology and cryptocurrency with experts from the field.",
    "location": "Blockchain Center, 331 Crypto Blvd, San Francisco, CA 94107",
    "date_time": "2025-11-15T11:00:00Z",
    "user_id": 1
}
