PUT http://localhost:8080/events/5
Content-Type: application/json

{
    "name": "Blockchain and Cryptocurrency Workshop",
    "description": "Dive into the world of blockchain technology and cryptocurrency with experts from the field.",
    "location": "Blockchain Center, 331 Crypto Blvd, San Francisco, CA 94107",
    "date_time": "2025-11-15T11:00:00Z",
    "user_id": 1
}
